CREATE OR REPLACE VIEW TOP10_ARTICLE_PAR_MOIS_ANNEE AS
WITH ventes_agg AS (
    SELECT
        EXTRACT(YEAR FROM DATERESERVATION) AS ANNEE,
        TO_CHAR(DATERESERVATION, 'Month', 'NLS_DATE_LANGUAGE=FRENCH') AS MOIS,
        TO_NUMBER(TO_CHAR(DATERESERVATION, 'MM')) AS MOISINT,
        IDPRODUITLIB,
        SUM(NVL(MONTANT, 0)) AS qteJour
    FROM
        VENTE_DETAILS_CPL
    WHERE
        DATERESERVATION IS NOT NULL
        AND UPPER(TRIM(IDPRODUITLIB)) NOT IN (
            'TRANSPORT ALLER',
            'TRANSPORT PERS',
            'CAUTION',
            'TRANSPORT RETOUR'
        )
    GROUP BY
        EXTRACT(YEAR FROM DATERESERVATION),
        TO_CHAR(DATERESERVATION, 'Month', 'NLS_DATE_LANGUAGE=FRENCH'),
        TO_NUMBER(TO_CHAR(DATERESERVATION, 'MM')),
        IDPRODUITLIB
)
SELECT
    '' AS ID,
    RANG,
    ANNEE,
    INITCAP(RTRIM(MOIS)) AS MOIS,
    MOISINT,
    IDPRODUITLIB,
    qteJour,
    CASE
        WHEN RANG <= 3 THEN 3
        WHEN RANG <= 5 THEN 5
        ELSE 10
        END AS TOP
FROM (
         SELECT
             v.*,
             RANK() OVER (PARTITION BY ANNEE, MOIS ORDER BY qteJour DESC) AS RANG
         FROM
             ventes_agg v
     )
WHERE
    RANG <= 10
ORDER BY
    ANNEE DESC,
    MOISINT DESC,
    qteJour DESC;