CREATE OR REPLACE VIEW V_PROFORMAMERE_DATE AS
SELECT m.id as IDMERE,
       MIN(f.DATEDEBUT) AS DATEDEBUT_MIN,
       MAX(f.DATEDEBUT+f.QTE -1)   AS DATEFIN_MAX
FROM PROFORMA m
         LEFT JOIN PROFORMA_DETAILS f
                   ON m.id = f.IDPROFORMA
GROUP BY m.id;

DELETE FROM MENUDYNAMIQUE
WHERE ID='ELM001104005';

UPDATE MENUDYNAMIQUE
SET RANG=1
WHERE ID='ELM001104006';

UPDATE MENUDYNAMIQUE
SET RANG=2
WHERE ID='ELM001504001';

UPDATE MENUDYNAMIQUE
SET RANG=3
WHERE ID='ELM01';