CREATE OR REPLACE VIEW ca_par_mois AS
SELECT
    '' AS id,
    INITCAP(TO_CHAR(DATY, 'Month YYYY', 'NLS_DATE_LANGUAGE=FRENCH')) AS MOIS,
    TRUNC(DATY, 'MM') AS DEBUT,
    SUM(MONTANTTOTAL) AS CA
FROM
    VENTE_CPL
WHERE
        ETAT >= 11
GROUP BY
    TO_CHAR(DATY, 'Month YYYY', 'NLS_DATE_LANGUAGE=FRENCH'),
    TRUNC(DATY, 'MM')
ORDER BY
    DEBUT;

CREATE OR REPLACE VIEW TOP10_CLIENTS_PAR_MOIS_ANNEE AS
WITH ventes_agg AS (
    SELECT
        EXTRACT(YEAR FROM DATY) AS ANNEE,
        TO_CHAR(DATY, 'Month', 'NLS_DATE_LANGUAGE=FRENCH') AS MOIS,
        TO_NUMBER(TO_CHAR(DATY, 'MM')) AS MOISINT,
        IDCLIENTLIB,
        SUM(MONTANTTOTAL) AS CA
    FROM
        VENTE_CPL
    WHERE
        ETAT >= 11
    GROUP BY
        EXTRACT(YEAR FROM DATY),
        TO_CHAR(DATY, 'Month', 'NLS_DATE_LANGUAGE=FRENCH'),
        TO_NUMBER(TO_CHAR(DATY, 'MM')),
        TO_CHAR(DATY, 'YYYY-MM'),
        IDCLIENT,
        IDCLIENTLIB
)
SELECT
    '' AS ID,
    RANG,
    ANNEE,
    INITCAP(RTRIM(MOIS)) AS MOIS,
    MOISINT,
    IDCLIENTLIB,
    CA
FROM (
         SELECT
             v.*,
             RANK() OVER (PARTITION BY ANNEE, MOIS ORDER BY CA DESC) AS RANG
         FROM
             ventes_agg v
     )
WHERE
        RANG <= 10
ORDER BY
    ANNEE DESC,
    MOISINT DESC,
    CA DESC;

CREATE OR REPLACE VIEW TOP10_ARTICLE_PAR_MOIS_ANNEE AS
WITH ventes_agg AS (
    SELECT
        EXTRACT(YEAR FROM DATERESERVATION) AS ANNEE,
        TO_CHAR(DATERESERVATION, 'Month', 'NLS_DATE_LANGUAGE=FRENCH') AS MOIS,
        TO_NUMBER(TO_CHAR(DATERESERVATION, 'MM')) AS MOISINT,
        IDPRODUITLIB,
        SUM(NVL(NOMBRE, 0)) AS qteJour
    FROM
        VENTE_DETAILS_CPL
    WHERE
        DATERESERVATION IS NOT NULL
    GROUP BY
        EXTRACT(YEAR FROM DATERESERVATION),
        TO_CHAR(DATERESERVATION, 'Month', 'NLS_DATE_LANGUAGE=FRENCH'),
        TO_NUMBER(TO_CHAR(DATERESERVATION, 'MM')),
        IDPRODUITLIB
)
SELECT
    '' AS ID,
    RANG,
    ANNEE,
    INITCAP(RTRIM(MOIS)) AS MOIS,
    MOISINT,
    IDPRODUITLIB,
    qteJour,
    CASE
        WHEN RANG <= 3 THEN 3
        WHEN RANG <= 5 THEN 5
        ELSE 10
        END AS TOP
FROM (
         SELECT
             v.*,
             RANK() OVER (PARTITION BY ANNEE, MOIS ORDER BY qteJour DESC) AS RANG
         FROM
             ventes_agg v
     )
WHERE
        RANG <= 10
ORDER BY
    ANNEE DESC,
    MOISINT DESC,
    qteJour DESC;
