UPDATE usermenu SET interdit = NULL,refuser=NULL WHERE IDMENU ='MNDN0000000211';

ALTER TABLE TRANSFERTSTOCK  DROP CONSTRAINT TRANSFERTSTOCK_MAGAR_FK;
ALTER TABLE TRANSFERTSTOCK  DROP CONSTRAINT TRANSFERTSTOCK_MAGDEP_FK;

DROP TABLE TRANSFERTSTOCKDETAILS
CREATE TABLE TRANSFERTSTOCKDETAILS 
   (	ID VARCHAR2(255), 
	IDTRANSFERTSTOCK VARCHAR2(255), 
	IDPRODUIT VARCHAR2(255), 
	QUANTITE NUMBER, 
	 CONSTRAINT TRANSFERTSTOCKDETAILS_PK PRIMARY KEY (ID),
	 CONSTRAINT TRANSFERTSTOCK_MEREFILLE_FK FOREIGN KEY (IDTRANSFERTSTOCK)
	  REFERENCES TRANSFERTSTOCK (ID) ENABLE NOVALIDATE
   ) ;
