-- ATIPIK2710.MODEPAIEMENT definition

CREATE TABLE typeclient 
   (	ID VARCHAR2(255), 
	VAL VARCHAR2(400), 
	DESCE VARCHAR2(400), 
	 CONSTRAINT typeclient_PK PRIMARY KEY (ID)
   ) ;

INSERT INTO TYPECLIENT
(ID, VAL, DESCE)
VALUES('TPC00001', 'Interne', 'Interne');

INSERT INTO TYPECLIENT
(ID, VAL, DESCE)
VALUES('TPC00002', 'Externe', 'Externe');

ALTER TABLE client ADD idtypeclient varchar2(100);

CREATE OR REPLACE VIEW V_INGREDIENTS_VIDE AS
SELECT
    i.ID,
    i.LIBELLE,
    i.SEUIL,
    i.UNITE,
    i.QUANTITEPARPACK,
    i.PU,
    i.ACTIF,
    i.PHOTO,
    i.CALORIE,
    i.DURRE,
    i.COMPOSE,
    i.CATEGORIEINGREDIENT,
    i.IDFOURNISSEUR,
    i.DATY,
    i.QTELIMITE,
    i.PV,
    i.LIBELLEVENTE,
    i.SEUILMIN,
    i.SEUILMAX,
    i.PUACHATUSD,
    i.PUACHATEURO,
    i.PUACHATAUTREDEVISE,
    i.PUVENTEUSD,
    i.PUVENTEEURO,
    i.PUVENTEAUTREDEVISE,
    i.ISVENTE,
    i.ISACHAT,
    i.COMPTE_VENTE,
    i.COMPTE_ACHAT,
    i.LIBELLEEXTACTE,
    i.TVA,
    i.COULEUR,
    i.NUMERO,
    i.GPS,
    i.REFERENCE,
    i.FILEPATH,
    i.IDMODELE,
    i.IDVOITURE,
    i.RESTE,
    i.TYPESTOCK,
    i.IMAGE,
    i.CLASSIFICATION,
    CAST(NULL AS VARCHAR2(50)) AS IDMAGASIN,
    CAST(NULL AS NUMBER(30,2)) AS QUANTITE
FROM AS_INGREDIENTS i
WHERE 1 = 0;
