CREATE OR REPLACE VIEW V_INGREDIENTS_VIDE AS
SELECT
    i.ID,
    i.LIBELLE,
    i.SEUIL,
    i.UNITE,
    i.QUANTITEPARPACK,
    i.DURRE,
    i.PU,
    i.ACTIF,
    i.PHOTO,
    i.CALORIE,
    i.COMPOSE,
    i.CATEGORIEINGREDIENT,
    i.IDFOURNISSEUR,
    i.DATY,
    i.QTELIMITE,
    i.PV,
    i.LIBELLEVENTE,
    i.SEUILMIN,
    i.SEUILMAX,
    i.PUACHATUSD,
    i.PUACHATEURO,
    i.PUACHATAUTREDEVISE,
    i.PUVENTEUSD,
    i.PUVENTEEURO,
    i.PUVENTEAUTREDEVISE,
    i.ISVENTE,
    i.ISACHAT,
    i.COMPTE_VENTE,
    i.COMPTE_ACHAT,
    i.LIBELLEEXTACTE,
    i.TVA,
    i.COULEUR,
    i.NUMERO,
    i.GPS,
    i.REFERENCE,
    i.FILEPATH,
    i.IDMODELE,
    i.IDVOITURE,
    i.RESTE,
    i.TYPESTOCK,
    i.IMAGE,
    i.CLASSIFICATION,
    CAST(NULL AS VARCHAR2(50)) AS IDMAGASIN,
    CAST(NULL AS NUMBER(30,2)) AS QUANTITE
FROM AS_INGREDIENTS i
WHERE 1 = 0;

CREATE OR REPLACE VIEW MVTSTOCKLIBARRIVAGE AS
SELECT
    *
FROM MVTSTOCKLIB m
WHERE IDOBJET IN ('ARRIVAGE');

CREATE OR REPLACE VIEW mvtstocklibcreerarrivage AS
SELECT
    *
FROM mvtstocklibcreer m
WHERE IDOBJET IN ('ARRIVAGE');

CREATE OR REPLACE VIEW mvtstocklibvaliderarrivage AS
SELECT
    *
FROM mvtstocklibvalider m
WHERE IDOBJET IN ('ARRIVAGE');