CREATE OR REPLACE VIEW CHECKINFORMU_BL AS
SELECT
    c."ID",c."RESERVATION",c."DATY",c."HEURE",c."REMARQUE",c."CLIENT",c."IDPRODUIT",c."ETAT",c."IDCLIENT",c."QTE",c."KILOMETRAGE",c."IDRESDETAIL",c."IDMAGASIN",c."RESPONSABLE",c."REFPRODUIT",c."IDTYPELIVRAISON",
    '' AS idclientlib, c.NUMBL
FROM checkin c;

CREATE OR REPLACE VIEW MVTSTOCKFILLELIB AS
SELECT
    m.ID ,
    m.IDMVTSTOCK ,
    m.IDPRODUIT ,
    p.libelle  AS IDPRODUITLIB,
    m.ENTREE ,
    m.SORTIE ,
    m.IDVENTEDETAIL ,
    '' AS IDVENTEDETAILLIB,
    m.IDTRANSFERTDETAIL ,
    '' AS IDTRANSFERTDETAILLIB,
    m2.DATY ,
    m2.IDMAGASIN ,
    m3.VAL AS IDMAGASINLIB,
    m.pu,
    cast(m.pu*m.ENTREE+(m.pu*m.sortie) as number(20,2)) as montant,
    p.LIBELLE,
    p.REFERENCE
FROM MVTSTOCKFILLE m
         LEFT JOIN AS_INGREDIENTS  p ON p.ID = m.IDPRODUIT
         LEFT JOIN MVTSTOCK m2 ON m2.ID = m.IDMVTSTOCK
         LEFT JOIN MAGASIN m3 ON m3.ID = m2.IDMAGASIN;