
ALTER TABLE proforma ADD numproforma VARCHAR2(100);

CREATE OR REPLACE VIEW ST_INGREDIENTSAUTOVENTE_M ("ID", "LIBELLE", "SEUIL", "UNITE", "QUANTITEPARPACK", "PU", "ACTIF", "PHOTO", "CALORIE", "DURRE", "COMPOSE", "CATEGORIEINGREDIENT", "IDFOURNISSEUR", "DATY", "QTELIMITE", "PV", "LIBELLEVENTE", "SEUILMIN", "SEUILMAX", "PUACHATUSD", "PUACHATEURO", "PUACHATAUTREDEVISE", "PUVENTEUSD", "PUVENTEEURO", "PUVENTEAUTREDEVISE", "ISVENTE", "ISACHAT", "COMPTE_VENTE", "COMPTE_ACHAT", "TVA", "COMPTE", "IDVOITURE", "IDMODELE", "QUANTITE","REFERENCE") AS 
  SELECT ai.ID,
       ai.LIBELLE,
       ai.SEUIL,
       ai.UNITE,
       ai.QUANTITEPARPACK,
       ai.PU,
       ai.ACTIF,
       ai.PHOTO,
       ai.CALORIE,
       ai.DURRE,
       ai.COMPOSE,
       ai.CATEGORIEINGREDIENT,
       ai.IDFOURNISSEUR,
       ai.DATY,
       ai.QTELIMITE,
       ai.PV,
       ai.LIBELLEVENTE,
       ai.SEUILMIN,
       ai.SEUILMAX,
       ai.PUACHATUSD,
       ai.PUACHATEURO,
       ai.PUACHATAUTREDEVISE,
       ai.PUVENTEUSD,
       ai.PUVENTEEURO,
       ai.PUVENTEAUTREDEVISE,
       ai.ISVENTE,
       ai.ISACHAT,
       ai.COMPTE_VENTE,
       ai.COMPTE_ACHAT,
       ai.TVA,
       ai.COMPTE_VENTE AS compte,
       ai.idvoiture,
       ai.IDMODELE,
       aimg.quantite,
       ai.reference
FROM AS_INGREDIENTS ai left join as_ingredient_m_grp aimg on aimg.IDMODELE = ai.id
where ai.pv > 0 and ai.IDMODELE = ai.id;

ALTER TABLE VENTE 
ADD (
    CAUTION     NUMBER(5,2),
    NUMFACTURE  VARCHAR2(100)
);

CREATE OR REPLACE VIEW INSERTION_VENTE ("ID", "DESIGNATION", "IDMAGASIN", "DATY", "REMARQUE", "ETAT", "IDORIGINE", "IDCLIENT", "IDDEVISE", "ESTPREVU", "DATYPREVU", "IDRESERVATION","CAUTION") AS 
  SELECT
	v.ID,
	v.DESIGNATION,
	v.IDMAGASIN,
	v.DATY,
	v.REMARQUE,
	v.ETAT,
	v.IDORIGINE,
	v.IDCLIENT,
	CAST(' ' AS varchar(100)) AS iddevise,
	v.ESTPREVU,
	v.DATYPREVU,
	v.IDRESERVATION,
	v.CAUTION 
FROM VENTE v;