-- SIHRAKT.MVTSTOCKENTREEAVECRESTE source

CREATE OR REPLACE  VIEW MVTSTOCKENTREEAVECRESTE (ID, IDMVTSTOCK, IDPRODUIT, ENTREE, SORTIE, IDVENTEDETAIL, IDTRANSFERTDETAIL, PU, MVTSRC, DATY, RESTE, QUANTITE, IDMAGASIN) AS 
  SELECT
	m.ID,
	m.IDMVTSTOCK,
	m.IDPRODUIT,
	m.ENTREE,
	s.SORTIE,
	m.IDVENTEDETAIL,
	m.IDTRANSFERTDETAIL,
	m.PU,
	m.MVTSRC,
	mp.DATY,
	NVL(m.entree,0)- NVL(s.sortie, 0) AS reste,
	NVL(m.entree,0)- NVL(s.sortie, 0) AS quantite,
	--ity no reste miasa any
 mp.IDMAGASIN
FROM
	MVTSTOCKFILLE m
LEFT JOIN MVTSTOCK mp ON
	mp.id = m.IDMVTSTOCK
LEFT JOIN sortieEntree s ON
	s.MVTSRC = m.id 
WHERE
	m.ENTREE >0
	AND mp.ETAT >= 11;
	

UPDATE AS_INGREDIENTS ai
SET ai.RESTE = (
    SELECT SUM(v.reste)
    FROM V_ETATSTOCK_ING v
    WHERE v.ID = ai.ID
);

Update AS_INGREDIENTS ai SET TYPESTOCK='CUMP' where 1=1
