alter table VENTE_DETAILS
    drop constraint VENTE_DETAILS_PRODUIT_FK;

CREATE OR REPLACE VIEW "OFABLIB" ("ID", "LANCEPAR", "CIBLE", "REMARQUE", "LIBELLE", "BESOIN", "DATY", "ETAT")AS

SELECT ofl.ID, 
	p1.VAL  AS LANCEPAR, 
	p2.VAL  AS CIBLE, 
	ofl.REMARQUE, 
	ofl.LIBELLE, 
	ofl.BESOIN, 
	ofl.DATY, 
	ofl.ETAT
FROM OFAB ofl
	LEFT JOIN POINT p1 ON p1.ID = ofl.LANCEPAR 
	LEFT JOIN POINT p2 ON p2.ID = ofl.CIBLE;

    CREATE OR REPLACE VIEW OfFilleLib AS
SELECT
	ofll.ID,
	ofll.IDINGREDIENTS,
	ai.LIBELLE ||' '|| ofll.LIBELLE as LIBELLE,
	ofll.REMARQUE,
	ofll.IDMERE,
	ofll.DATYBESOIN,
	ofll.QTE,
	nvl(au.VAL,'unite') AS IDUNITE
FROM OFFILLE ofll
	LEFT JOIN AS_INGREDIENTS ai ON ai.ID = ofll.IDINGREDIENTS
	LEFT JOIN AS_UNITE au ON au.ID = ofll.IDUNITE
;