ALTER TABLE AS_BONDELIVRAISON  DROP CONSTRAINT BL_MAGASIN_FK;
ALTER TABLE AS_BONDELIVRAISON_FILLE DROP CONSTRAINT SYS_C0024464;


CREATE OR REPLACE  VIEW AS_BONDELIVRAISON_LIBCPL (ID, PRODUIT, NUMBL, QUANTITE, IDDETAILSFACTUREFOURNISSEUR, UNITE, IDBC_FILLE, REMARQUE, IDBC, DATY, ETAT, MAGASIN, PRODUITLIB, UNITELIB, MAGASINLIB) AS 
  select bl.ID,bl.PRODUIT,bl.NUMBL,bl.QUANTITE,bl.IDDETAILSFACTUREFOURNISSEUR,bl.UNITE,bl.IDBC_FILLE,
       AB.REMARQUE,
       AB.IDBC,
       AB.DATY,
       AB.ETAT,
       AB.MAGASIN,
       p.libelle as PRODUITlib,
       u.VAL as UNITElib,
       m.VAL as magasinlib
from As_BonDeLivraison_Fille bl
         left join AS_BONDELIVRAISON AB on AB.ID = bl.NUMBL
         left join AS_INGREDIENTS  p on bl.PRODUIT = p.ID
         left join UNITE u on bl.UNITE = u.ID
         left join MAGASIN m on ab.MAGASIN = m.ID
        ;