

--INSERER PRODUIT DE BASE (PV=0)


INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421001', '71001', '71001', '1', '7', NULL, 'COMP000039');

INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421002', '61001', '61001', '1', '6', NULL, 'COMP000067');



--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0011', 'farine de blé', 0, 'UNT00001', 0, 4, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001 

UPDATE AS_INGREDIENTS
SET LIBELLE='farine de blé', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=4, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71001', COMPTE_ACHAT='61001'
WHERE ID='PB0011';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0012', 'farine  complète', 0, 'UNT00001', 0, 5, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001 

UPDATE AS_INGREDIENTS
SET LIBELLE='farine  complète', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=5, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71002', COMPTE_ACHAT='61002'
WHERE ID='PB0012';



--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0013', 'farine  sans gluten', 0, 'UNT00001', 0, 6, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001

UPDATE AS_INGREDIENTS
SET LIBELLE='farine  sans gluten', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=6, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71003', COMPTE_ACHAT='61003'
WHERE ID='PB0013';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0014', 'levure fraîche', 0, 'UNT00001', 0, 1, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001

UPDATE AS_INGREDIENTS
SET LIBELLE='levure fraîche', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71004', COMPTE_ACHAT='61004'
WHERE ID='PB0014';



--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0015', 'levure chimique', 0, 'UNT00001', 0, 1, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001

UPDATE AS_INGREDIENTS
SET LIBELLE='levure chimique', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71005', COMPTE_ACHAT='61005'
WHERE ID='PB0015';



--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0016', 'levure sèche', 0, 'UNT00001', 0, 1, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001

UPDATE AS_INGREDIENTS
SET LIBELLE='levure sèche', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71006', COMPTE_ACHAT='61006'
WHERE ID='PB0016';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0017', 'eau', 0, 'UNT00006', 0, 1000, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--);71001 , 61001 

UPDATE AS_INGREDIENTS
SET LIBELLE='eau', SEUIL=0, UNITE='UNT00006', QUANTITEPARPACK=0, PU=1000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71007', COMPTE_ACHAT='61007'
WHERE ID='PB0017';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0018', 'sel', 0, 'UNT00001', 0, 2, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001


UPDATE AS_INGREDIENTS
SET LIBELLE='sel', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=2, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71008', COMPTE_ACHAT='61008'
WHERE ID='PB0018';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0019', 'sucre', 0, 'UNT00001', 0, 4, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001 

UPDATE AS_INGREDIENTS
SET LIBELLE='sucre', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=4, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71009', COMPTE_ACHAT='61009'
WHERE ID='PB0019';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0020', 'lait', 0, 'UNT00004', 0, 3, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001 

UPDATE AS_INGREDIENTS
SET LIBELLE='lait', SEUIL=0, UNITE='UNT00004', QUANTITEPARPACK=0, PU=3, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710010', COMPTE_ACHAT='610010'
WHERE ID='PB0020';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0021', 'oeuf', 0, 'UNT00005', 0, 1, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001

UPDATE AS_INGREDIENTS
SET LIBELLE='oeuf', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=500, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710011', COMPTE_ACHAT='610011'
WHERE ID='PB0021';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0022', 'sesame', 0, 'UNT00001', 0, 8, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001

UPDATE AS_INGREDIENTS
SET LIBELLE='sesame', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=8, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710012', COMPTE_ACHAT='610012'
WHERE ID='PB0022';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PB0023', 'amande', 0, 'UNT00001', 0, 12, 1, '', 0, 0, 0, 'CAT001', '', '', 0, 0
--); 71001 , 61001

UPDATE AS_INGREDIENTS
SET LIBELLE='amande', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710013', COMPTE_ACHAT='610013'
WHERE ID='PB0023';

--INSERER SERVICE
INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421003', '72001', '72001', '1', '7', NULL, 'COMP000039');

INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421004', '62001', '62001', '1', '6', NULL, 'COMP000067');

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('S0001', 'petrissage', 0, 'UNT00005', 0, 10000, 1, '', 0, 0, 0, 'CAT004', '', '', 0, 0
--); 72001 , 62001 

UPDATE AS_INGREDIENTS
SET LIBELLE='petrissage', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=10, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT004', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72001', COMPTE_ACHAT='62001'
WHERE ID='S0001';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('S0002', 'façonnage', 0, 'UNT00005', 0, 10000, 1, '', 0, 0, 0, 'CAT004', '', '', 0, 0
--);72001 , 62001 

UPDATE AS_INGREDIENTS
SET LIBELLE='façonnage', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=10000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT004', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72002', COMPTE_ACHAT='62002'
WHERE ID='S0002';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('S0003', 'cuisson four', 0, 'UNT00009', 0, 2, 1, '', 0, 0, 0, 'CAT006', '', '', 0, 0
--);72001 , 62001 

UPDATE AS_INGREDIENTS
SET LIBELLE='cuisson four', SEUIL=0, UNITE='UNT00009', QUANTITEPARPACK=0, PU=2, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT006', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72003', COMPTE_ACHAT='62003'
WHERE ID='S0003';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('S0004', 'cuisson', 0, 'UNT00009', 0, 1, 1, '', 0, 0, 0, 'CAT005', '', '', 0, 0
--);72001 , 62001 

UPDATE AS_INGREDIENTS
SET LIBELLE='cuisson', SEUIL=0, UNITE='UNT00009', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT005', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72004', COMPTE_ACHAT='62004'
WHERE ID='S0004';




--INSERER PRODUITS FABRIQUES
INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421005', '73001', '73001', '1', '7', NULL, 'COMP000039');

INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421006', '63001', '63001', '1', '6', NULL, 'COMP000067');



--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PF0011', 'pâte standard', 0, 'UNT00001', 0, 8, 1, '', 0, 0, 1, 'CAT007', '', '', 0, 10
--);73001 , 63001 

UPDATE AS_INGREDIENTS
SET LIBELLE='pâte standard', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=8, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=10, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73001', COMPTE_ACHAT='63001'
WHERE ID='PF0011';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PF0012', 'pâte complète', 0, 'UNT00001', 0, 10, 1, '', 0, 0, 1, 'CAT007', '', '', 0, 12
--);73001 , 63001 

UPDATE AS_INGREDIENTS
SET LIBELLE='pâte complète', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=10, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=12, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73002', COMPTE_ACHAT='63002'
WHERE ID='PF0012';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PF0013', 'pâte sans gluten', 0, 'UNT00001', 0, 12, 1, '', 0, 0, 1, 'CAT007', '', '', 0, 14
--);73001 , 63001 

UPDATE AS_INGREDIENTS
SET LIBELLE='pâte sans gluten', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=14, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73003', COMPTE_ACHAT='63003'
WHERE ID='PF0013';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PF0014', 'pâte viennoiserie', 0, 'UNT00001', 0, 18, 1, '', 0, 0, 1, 'CAT007', '', '', 0, 20
--);73001 , 63001 

UPDATE AS_INGREDIENTS
SET LIBELLE='pâte viennoiserie', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=18, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=20, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73004', COMPTE_ACHAT='63004'
WHERE ID='PF0014';

--INSERER PRODUIT DE VENTE

INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421007', '74001', '74001', '1', '7', NULL, 'COMP000039');

INSERT INTO COMPTA_COMPTE
(ID, COMPTE, LIBELLE, TYPECOMPTE, CLASSY, ANALYTIQUE_OBLI, IDJOURNAL)
VALUES('COC001421008', '64001', '64001', '1', '6', NULL, 'COMP000067');

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PV0014', 'baguette', 0, 'UNT00005', 0, 3000, 1, '', 0, 0, 1, 'CAT002', '', '', 0, 4000
--);74001 , 64001 

UPDATE AS_INGREDIENTS
SET LIBELLE='baguette', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=3000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=4000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74001', COMPTE_ACHAT='64001'
WHERE ID='PV0014';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PV0015', 'pain complet', 0, 'UNT00005', 0, 6000, 1, '', 0, 0, 1, 'CAT002', '', '', 0, 8000
--);74001 , 64001 

UPDATE AS_INGREDIENTS
SET LIBELLE='pain complet', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=6000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74002', COMPTE_ACHAT='64002'
WHERE ID='PV0015';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PV0016', 'baguette sans gluten', 0, 'UNT00005', 0, 8000, 1, '', 0, 0, 1, 'CAT002', '', '', 0, 12000
--); 74001 , 64001 

UPDATE AS_INGREDIENTS
SET LIBELLE='baguette sans gluten', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=8000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=12000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74003', COMPTE_ACHAT='64003'
WHERE ID='PV0016';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PV0017', 'pain sesame', 0, 'UNT00005', 0, 6000, 1, '', 0, 0, 1, 'CAT002', '', '', 0, 8000
--) ; 74001 , 64001 

UPDATE AS_INGREDIENTS
SET LIBELLE='pain sesame', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=6000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74004', COMPTE_ACHAT='64004'
WHERE ID='PV0017';


--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PV0018', 'croissant', 0, 'UNT00005', 0, 5000, 1, '', 0, 0, 1, 'CAT003', '', '', 0, 8000
--); 74001 , 64001 

UPDATE AS_INGREDIENTS
SET LIBELLE='croissant', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=5000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT003', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74005', COMPTE_ACHAT='64005'
WHERE ID='PV0018';

--INSERT INTO AS_INGREDIENTS
--(ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, CATEGORIEINGREDIENT, IDFOURNISSEUR, DATY, QTELIMITE, PV)
--VALUES('PV0019', 'croissant aux amandes', 0, 'UNT00005', 0, 7000, 1, '', 0, 0, 1, 'CAT003', '', '', 0, 9000
--);; 74001 , 64001 

UPDATE AS_INGREDIENTS
SET LIBELLE='croissant aux amandes', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=8000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT=NULL, IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=9000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74006', COMPTE_ACHAT='64006'
WHERE ID='PV0019';