------ 2025-04-07
------------Tiavina

-----Ajout libelleextacte 

ALTER TABLE AS_INGREDIENTS ADD libelleextacte VARCHAR(250);

UPDATE AS_INGREDIENTS
SET LIBELLE='farine de ble', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=11, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71001', COMPTE_ACHAT='61001', LIBELLEEXTACTE='farine de bl&eacute;'
WHERE ID='PB0011';

UPDATE AS_INGREDIENTS
SET LIBELLE='farine  complete', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71002', COMPTE_ACHAT='61002', LIBELLEEXTACTE='farine  compl&egrave;te'
WHERE ID='PB0012';

UPDATE AS_INGREDIENTS
SET LIBELLE='farine  sans gluten', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=6, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71003', COMPTE_ACHAT='61003', LIBELLEEXTACTE='farine  sans gluten'
WHERE ID='PB0013';

UPDATE AS_INGREDIENTS
SET LIBELLE='levure fraiche', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71004', COMPTE_ACHAT='61004', LIBELLEEXTACTE='levure fra&icirc;che'
WHERE ID='PB0014';

UPDATE AS_INGREDIENTS
SET LIBELLE='levure chimique', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71005', COMPTE_ACHAT='61005', LIBELLEEXTACTE='levure chimique'
WHERE ID='PB0015';

UPDATE AS_INGREDIENTS
SET LIBELLE='levure seche', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71006', COMPTE_ACHAT='61006', LIBELLEEXTACTE='levure s&egrave;che'
WHERE ID='PB0016';

UPDATE AS_INGREDIENTS
SET LIBELLE='eau', SEUIL=0, UNITE='UNT00006', QUANTITEPARPACK=0, PU=1000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71007', COMPTE_ACHAT='61007', LIBELLEEXTACTE='eau'
WHERE ID='PB0017';

UPDATE AS_INGREDIENTS
SET LIBELLE='sel', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=2, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71008', COMPTE_ACHAT='61008', LIBELLEEXTACTE='sel'
WHERE ID='PB0018';

UPDATE AS_INGREDIENTS
SET LIBELLE='sucre', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=4, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71009', COMPTE_ACHAT='61009', LIBELLEEXTACTE='sucre'
WHERE ID='PB0019';

UPDATE AS_INGREDIENTS
SET LIBELLE='lait', SEUIL=0, UNITE='UNT00004', QUANTITEPARPACK=0, PU=3, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710010', COMPTE_ACHAT='610010', LIBELLEEXTACTE='lait'
WHERE ID='PB0020';

UPDATE AS_INGREDIENTS
SET LIBELLE='oeuf', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=500, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710011', COMPTE_ACHAT='610011', LIBELLEEXTACTE='&oelig;uf'
WHERE ID='PB0021';

UPDATE AS_INGREDIENTS
SET LIBELLE='sesame', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=8, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710012', COMPTE_ACHAT='610012', LIBELLEEXTACTE='s&eacute;same'
WHERE ID='PB0022';

UPDATE AS_INGREDIENTS
SET LIBELLE='amande', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710013', COMPTE_ACHAT='610013', LIBELLEEXTACTE='amande'
WHERE ID='PB0023';

UPDATE AS_INGREDIENTS
SET LIBELLE='petrissage', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=10, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT004', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72001', COMPTE_ACHAT='62001', LIBELLEEXTACTE='p&eacute;trissage'
WHERE ID='S0001';

UPDATE AS_INGREDIENTS
SET LIBELLE='faconnage', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=10000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT004', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72002', COMPTE_ACHAT='62002', LIBELLEEXTACTE='fa&ccedil;onnage'
WHERE ID='S0002';

UPDATE AS_INGREDIENTS
SET LIBELLE='cuisson four', SEUIL=0, UNITE='UNT00009', QUANTITEPARPACK=0, PU=2, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT006', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72003', COMPTE_ACHAT='62003', LIBELLEEXTACTE='cuisson four'
WHERE ID='S0003';

UPDATE AS_INGREDIENTS
SET LIBELLE='cuisson', SEUIL=0, UNITE='UNT00009', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT005', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72004', COMPTE_ACHAT='62004', LIBELLEEXTACTE='cuisson'
WHERE ID='S0004';

UPDATE AS_INGREDIENTS
SET LIBELLE='pâte standard', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=8, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=10, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73001', COMPTE_ACHAT='63001', LIBELLEEXTACTE='p&acirc;te standard'
WHERE ID='PF0011';

UPDATE AS_INGREDIENTS
SET LIBELLE='pate complete', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=10, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=12, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73002', COMPTE_ACHAT='63002', LIBELLEEXTACTE='p&acirc;te compl&egrave;te'
WHERE ID='PF0012';

UPDATE AS_INGREDIENTS
SET LIBELLE='pate sans gluten', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=14, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73003', COMPTE_ACHAT='63003', LIBELLEEXTACTE='p&acirc;te sans gluten'
WHERE ID='PF0013';

UPDATE AS_INGREDIENTS
SET LIBELLE='pate viennoiserie', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=18, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=20, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73004', COMPTE_ACHAT='63004', LIBELLEEXTACTE='p&acirc;te viennoiserie'
WHERE ID='PF0014';

UPDATE AS_INGREDIENTS
SET LIBELLE='baguette', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=3000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=4000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74001', COMPTE_ACHAT='64001', LIBELLEEXTACTE='baguette'
WHERE ID='PV0014';

UPDATE AS_INGREDIENTS
SET LIBELLE='pain complet', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=6000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8001, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74002', COMPTE_ACHAT='64002', LIBELLEEXTACTE='pain complet'
WHERE ID='PV0015';

UPDATE AS_INGREDIENTS
SET LIBELLE='baguette sans gluten', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=8000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=12000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74003', COMPTE_ACHAT='64003', LIBELLEEXTACTE='baguette sans gluten'
WHERE ID='PV0016';

UPDATE AS_INGREDIENTS
SET LIBELLE='pain sesame', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=6000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74004', COMPTE_ACHAT='64004', LIBELLEEXTACTE='pain s&eacute;same'
WHERE ID='PV0017';

UPDATE AS_INGREDIENTS
SET LIBELLE='croissant', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=5000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT003', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74005', COMPTE_ACHAT='64005', LIBELLEEXTACTE='croissant'
WHERE ID='PV0018';

UPDATE AS_INGREDIENTS
SET LIBELLE='croissant aux amandes', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=8000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT003', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=9000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74006', COMPTE_ACHAT='64006', LIBELLEEXTACTE='croissant aux amandes'
WHERE ID='PV0019';


CREATE OR REPLACE  VIEW PRODUIT_LIB (ID, VAL, DESCE, IDTYPEPRODUIT, IDTYPEPRODUITLIB, PUACHAT, PUVENTE, IDUNITE, IDUNITELIB, IDCATEGORIE, IDCATEGORIELIB, IDSOUSCATEGORIELIB, SEUILMIN, SEUILMAX, PUACHATUSD, PUACHATEURO, PUACHATAUTREDEVISE, PUVENTEUSD, PUVENTEEURO, PUVENTEAUTREDEVISE, ISVENTE, ISACHAT, COMPTE_VENTE, COMPTE_ACHAT) AS 
  SELECT p.ID,
       p.libelleextacte as val,
       p.libelleextacte as DESCE,
       '-' as IDTYPEPRODUIT,
       '-' AS IDTYPEPRODUITLIB,
       p.PU as PUACHAT,
       p.pv as PUVENTE,
       p.UNITE as idunite,
       u.VAL  AS IDUNITELIB,
       p.CATEGORIEINGREDIENT as IDCATEGORIE,
       c.VAL  AS IDCATEGORIELIB,
       '-'  AS IDSOUSCATEGORIELIB,
       p.seuilmin,
       p.seuilmax,
       p.puAchatUsd,
  	   p.puAchatEuro,
	   p.puAchatAutreDevise,
	   p.puVenteUsd,
	   p.puVenteEuro,
	   p.puVenteAutreDevise,
	   p.isvente,
	   p.isachat,
	   p.compte_vente,
	   p.compte_achat
FROM AS_INGREDIENTS p
         LEFT JOIN CATEGORIEINGREDIENT c ON c.ID = p.CATEGORIEINGREDIENT
         LEFT JOIN as_UNITE u ON u.ID = p.unite;
         
        

CREATE OR REPLACE  VIEW AS_INGREDIENTS_LIB (ID, LIBELLE, SEUIL, UNITE, QUANTITEPARPACK, PU, ACTIF, PHOTO, CALORIE, DURRE, COMPOSE, IDCATEGORIEINGREDIENT, CATEGORIEINGREDIENT, IDCATEGORIE, IDFOURNISSEUR, DATY, BIENOUSERV, ETATLIB, COMPTE_VENTE, COMPTE_ACHAT) AS 
  SELECT ing.id,
          ing.libelleextacte,
          ing.SEUIL,
          au.VAL AS unite,
          ing.QUANTITEPARPACK,
          ing.pu,
          ing.ACTIF,
          ing.PHOTO,
          ing.CALORIE,
          ing.DURRE,
          ing.COMPOSE,
          cating.id AS IDCATEGORIEINGREDIENT ,
          catIng.VAL AS CATEGORIEINGREDIENT,
          ing.CATEGORIEINGREDIENT AS idcategorie,
          ing.idfournisseur,
          ing.daty,
          catIng.desce as bienOuServ,
	      CASE WHEN ing.id IN (SELECT idproduit FROM INDISPONIBILITE i )
	      THEN 'INDISPONIBLE'
	      WHEN ing.id NOT IN (SELECT idproduit FROM INDISPONIBILITE i )
	      THEN 'DISPONIBLE'
	      END AS etatlib,
        ing.COMPTE_VENTE,
        ing.COMPTE_ACHAT

     FROM as_ingredients ing
          JOIN AS_UNITE AU ON ing.UNITE = AU.ID
          JOIN CATEGORIEINGREDIENTLIB catIng
             ON catIng.id = ing.CATEGORIEINGREDIENT;
             
            

         
         
UPDATE VENTE_DETAILS
SET IDVENTE='VNT000640222107', IDPRODUIT='PF0011', IDORIGINE=NULL, QTE=50, PU=10, REMISE=4, TVA=0, PUACHAT=0, PUVENTE=0, IDDEVISE='AR', TAUXDECHANGE=1, DESIGNATION='p&acirc;te standard', COMPTE='73001'
WHERE ID='VTD000639222107';
            
 UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au Facture d avoir NAVRFC000085', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=5, DATY=TIMESTAMP '2024-09-16 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='AVRFC000085'
WHERE ID='MTC000687113836';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000610165618', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=30000, DATY=TIMESTAMP '2024-12-16 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000610165618'
WHERE ID='MTC000753102926';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000634162040', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=6000, DATY=TIMESTAMP '2025-04-02 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000634162040'
WHERE ID='MTC000755162049';


UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000638125808', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=30000, DATY=TIMESTAMP '2025-04-07 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000638125808'
WHERE ID='MTC000777132138';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000323', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=3800, CREDIT=0, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000323'
WHERE ID='MTC000780171547';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000324', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=75, CREDIT=0, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000324'
WHERE ID='MTC000781174752';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000639190501', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=55000, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000639190501'
WHERE ID='MTC000785190508';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000591004800', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=10000, DATY=TIMESTAMP '2024-09-12 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE=NULL, TAUX=1, IDTIERS='CLI000054', COMPTE=NULL, IDFACTURE='VNT000591004800'
WHERE ID='MTC000673004805';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000592171701', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=3000, DATY=TIMESTAMP '2024-09-09 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=0, IDTIERS='CLI000054', COMPTE=NULL, IDFACTURE='VNT000592171701'
WHERE ID='MTC000675171714';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000592171701', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=1997000, DATY=TIMESTAMP '2024-09-19 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=0, IDTIERS='CLI000054', COMPTE=NULL, IDFACTURE='VNT000592171701'
WHERE ID='MTC000675171714B';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au Facture d avoir NAVRFC000091', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=1, DATY=TIMESTAMP '2024-09-16 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='AVRFC000091'
WHERE ID='MTC000688124400';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au Facture d avoir NAVRFC000090', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=2, CREDIT=0, DATY=TIMESTAMP '2024-09-16 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='AVRFC000090'
WHERE ID='MTC000689124806';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au Facture d avoir NAVRFC000093', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=4900, CREDIT=0, DATY=TIMESTAMP '2024-09-16 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='AVRFC000093'
WHERE ID='MTC000691130757';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000325', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=210, CREDIT=0, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000325'
WHERE ID='MTC000782175432';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000326', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=1100, CREDIT=0, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000326'
WHERE ID='MTC000783175956';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000571170501', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=2000000, DATY=TIMESTAMP '2024-09-03 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE=NULL, TAUX=0, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000571170501'
WHERE ID='MTC000653170505';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000574190910', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=960000, DATY=TIMESTAMP '2024-09-03 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='EUR', TAUX=0, IDTIERS='CLI000054', COMPTE=NULL, IDFACTURE='VNT000574190910'
WHERE ID='MTC000654190937';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000281', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=1200000, CREDIT=0, DATY=TIMESTAMP '2024-09-09 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=0, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000281'
WHERE ID='MTC000682221154';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000593223700', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=2646000, DATY=TIMESTAMP '2024-09-12 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000593223700'
WHERE ID='MTC000684223718';



UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000632231227', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=30000, DATY=TIMESTAMP '2025-03-18 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000632231227'
WHERE ID='MTC000754203347';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000638125808', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=60000, DATY=TIMESTAMP '2025-05-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000638125808'
WHERE ID='MTC000777132138b';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000638125808', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=30000, DATY=TIMESTAMP '2025-06-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000638125808'
WHERE ID='MTC000777132138c';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000327', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=1100, CREDIT=0, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000327'
WHERE ID='MTC000784180018';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au Facture d avoir NAVRFC000092', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=1, CREDIT=0, DATY=TIMESTAMP '2024-09-16 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='AVRFC000092'
WHERE ID='MTC000690125840';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000640222107', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=480, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000640222107'
WHERE ID='MTC000788222611';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000263', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=30000, CREDIT=0, DATY=TIMESTAMP '2024-08-28 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE=NULL, TAUX=0, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000263'
WHERE ID='MTC000633121019';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au vente NVNT000594225457', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=0, CREDIT=11025000, DATY=TIMESTAMP '2024-09-16 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='VNT000594225457'
WHERE ID='MTC000685225505';
UPDATE PREVISION
SET DESIGNATION='Pr&eacute;vision rattach&eacute;e au FF NFCF000328', IDCAISSE='CAI000238', IDVENTEDETAIL=NULL, IDVIREMENT=NULL, DEBIT=180, CREDIT=0, DATY=TIMESTAMP '2025-04-06 00:00:00.000000', ETAT=1, IDOP=NULL, IDORIGINE=NULL, IDDEVISE='AR', TAUX=1, IDTIERS=NULL, COMPTE=NULL, IDFACTURE='FCF000328'
WHERE ID='MTC000790231249';

---- jointure idmagasinlib

CREATE OR REPLACE  VIEW AS_BONDELIVRAISONCLIENT_LIBCPL (ID, REMARQUE, IDVENTE, IDBC, DATY, ETAT, MAGASIN, IDORIGINE, IDCLIENT, IDMAGASINLIB, IDCLIENTLIB, ETATLIB) AS 
  select ab.ID,ab.REMARQUE,ab.IDVENTE,ab.IDBC,ab.DATY,ab.ETAT,ab.MAGASIN,ab.IDORIGINE,ab.IDCLIENT, 
m.val AS idmagasinlib,
 c.nom AS idclientlib,
CASE
    WHEN ab.ETAT = 0 THEN '<span style=color: green;>ANNULEE</span>'
    WHEN ab.ETAT = 1 THEN '<span style=color: green;>CREE</span>'
    WHEN ab.ETAT = 11 THEN '<span style=color: green;>VALIDEE</span>'
END AS ETATLIB

from  AS_BONDELIVRAISON_CLIENT  AB
left join MAGASIN2 m on ab.MAGASIN = m.ID
LEFT JOIN client c ON c.id = ab.idclient
         ;


---ajout idingredientslibexacte

CREATE OR REPLACE  VIEW FABRICATIONFILLECPL (ID, IDINGREDIENTS, LIBELLE, REMARQUE, IDMERE, DATYBESOIN, QTE, IDUNITE, PU, IDINGREDIENTSLIB,idingredientslibexacte) AS 
SELECT
	f.ID,
	f.IDINGREDIENTS,
	f.LIBELLE,
	f.REMARQUE,
	f.IDMERE,
	f.DATYBESOIN,
	f.QTE,
	f.IDUNITE,
	f.PU,
	ai.LIBELLE AS idingredientsLib,
	ai.LIBELLEEXTACTE
FROM
	FABRICATIONFILLE f
LEFT JOIN AS_INGREDIENTS ai ON
	ai.id = f.IDINGREDIENTS;
	

UPDATE FABRICATIONFILLE
SET IDINGREDIENTS='PF0013', LIBELLE='p&acirc;te sans gluten ', REMARQUE=NULL, IDMERE='FAB000024', DATYBESOIN=NULL, QTE=2, IDUNITE='unite', PU=NULL
WHERE ID='FABF000025';
UPDATE FABRICATIONFILLE
SET IDINGREDIENTS='PF0013', LIBELLE='p&acirc;te sans gluten ', REMARQUE=NULL, IDMERE='FAB000025', DATYBESOIN=NULL, QTE=1, IDUNITE='unite', PU=NULL
WHERE ID='FABF000026';
UPDATE FABRICATIONFILLE
SET IDINGREDIENTS='PF0013', LIBELLE='p&acirc;te sans gluten ', REMARQUE=NULL, IDMERE='FAB000026', DATYBESOIN=NULL, QTE=1, IDUNITE='unite', PU=643
WHERE ID='FABF000027';
UPDATE FABRICATIONFILLE
SET IDINGREDIENTS='PF0012', LIBELLE='p&acirc;te compl&egrave;te ', REMARQUE=NULL, IDMERE='FAB000023', DATYBESOIN=NULL, QTE=5, IDUNITE='unite', PU=NULL
WHERE ID='FABF000023';
UPDATE FABRICATIONFILLE
SET IDINGREDIENTS='PB0011', LIBELLE='farine de bl&eacute; ', REMARQUE=NULL, IDMERE='FAB000023', DATYBESOIN=NULL, QTE=8, IDUNITE='unite', PU=NULL
WHERE ID='FABF000024';


--- ajout LIBELLEEXTACTE

CREATE OR REPLACE  VIEW OFFILLELIB (ID, IDINGREDIENTS, LIBELLE, REMARQUE, IDMERE, DATYBESOIN, QTE, IDUNITE, QTEFABRIQUE, QTERESTE,LIBELLEEXTACTE) AS 
  SELECT
	ofll.ID,
	ofll.IDINGREDIENTS,
	ai.LIBELLE ||' '|| ofll.LIBELLE as LIBELLE,
	ofll.REMARQUE,
	ofll.IDMERE,
	ofll.DATYBESOIN,
	ofll.QTE,
	nvl(au.VAL,'unite') AS IDUNITE,
	fmf.qte AS qteFabrique,(ofll.qte-nvl(fmf.qte,0)) AS qteReste,
	ai.LIBELLEEXTACTE
FROM OFFILLE ofll
	LEFT JOIN AS_INGREDIENTS ai ON ai.ID = ofll.IDINGREDIENTS
	LEFT JOIN AS_UNITE au ON au.ID = ofll.IDUNITE
    LEFT JOIN FabricationMereFille fmf on fmf.IDOF=ofll.IDMERE and fmf.IDINGREDIENTS=ofll.IDINGREDIENTS;
    
   

   CREATE OR REPLACE  VIEW OFFILLELIBQTERESTE (ID, IDINGREDIENTS, LIBELLE, REMARQUE, IDMERE, DATYBESOIN, QTE, IDUNITE, QTEFABRIQUE, QTERESTE, LIBELLEMERE, DATY,LIBELLEEXTACTE) AS 
  SELECT
	ofll.ID,
	ofll.IDINGREDIENTS,
	ai.LIBELLE ||' '|| ofll.LIBELLE as LIBELLE,
	ofll.REMARQUE,
	ofll.IDMERE,
	ofll.DATYBESOIN,
	(ofll.qte-nvl(fmf.qte,0)) as QTE,
	nvl(au.VAL,'unite') AS IDUNITE,
	fmf.qte AS qteFabrique,(ofll.qte-fmf.qte) AS qteReste,
	fmf.LIBELLE as libelleMere,fmf.daty,
	ai.LIBELLEEXTACTE
FROM OFFILLE ofll
	LEFT JOIN AS_INGREDIENTS ai ON ai.ID = ofll.IDINGREDIENTS
	LEFT JOIN AS_UNITE au ON au.ID = ofll.IDUNITE
    LEFT JOIN FabricationMereFille fmf on fmf.IDOF=ofll.IDMERE and fmf.IDINGREDIENTS=ofll.IDINGREDIENTS;
    
   
   
CREATE OR REPLACE  VIEW OfFilleLib (ID, IDINGREDIENTS, LIBELLE, REMARQUE, IDMERE, DATYBESOIN, QTE, IDUNITE,LIBELLEEXTACTE) AS 
  SELECT 
	ofll.ID,
	ai.LIBELLE AS IDINGREDIENTS, 
	ofll.LIBELLE, 
	ofll.REMARQUE, 
	ofll.IDMERE, 
	ofll.DATYBESOIN, 
	ofll.QTE, 
	nvl(au.VAL,'unite') AS IDUNITE,
	ai.LIBELLEEXTACTE
FROM OFFILLE ofll
	LEFT JOIN AS_INGREDIENTS ai ON ai.ID = ofll.IDINGREDIENTS 
	LEFT JOIN AS_UNITE au ON au.ID = ofll.IDUNITE 
;


CREATE OR REPLACE  VIEW MVTSTOCKFILLELIB (ID, IDMVTSTOCK, IDPRODUIT, IDPRODUITLIB, ENTREE, SORTIE, IDVENTEDETAIL, IDVENTEDETAILLIB, IDTRANSFERTDETAIL, IDTRANSFERTDETAILLIB, DATY, IDMAGASIN, IDMAGASINLIB, PU, MONTANT,LIBELLEEXTACTE) AS 
  SELECT
	m.ID ,
	m.IDMVTSTOCK ,
	m.IDPRODUIT ,
	p.libelle  AS IDPRODUITLIB,
	m.ENTREE ,
	m.SORTIE ,
	m.IDVENTEDETAIL ,
	'' AS IDVENTEDETAILLIB,
	m.IDTRANSFERTDETAIL ,
	'' AS IDTRANSFERTDETAILLIB,
	m2.DATY ,
	m2.IDMAGASIN ,
	m3.VAL AS IDMAGASINLIB,
	m.pu,
    cast(m.pu*m.ENTREE+(m.pu*m.sortie) as number(20,2)) as montant,
    p.LIBELLEEXTACTE
	FROM MVTSTOCKFILLE m
	LEFT JOIN AS_INGREDIENTS  p ON p.ID = m.IDPRODUIT
	LEFT JOIN MVTSTOCK m2 ON m2.ID = m.IDMVTSTOCK
	LEFT JOIN MAGASIN m3 ON m3.ID = m2.IDMAGASIN;


CREATE OR REPLACE  VIEW UPDATEVENTEDETAILS (ID, IDVENTE, IDPRODUIT, IDPRODUITLIB, IDORIGINE, QTE, PU, REMISE, TVA, PUACHAT, PUVENTE, IDDEVISE, TAUXDECHANGE, DESIGNATION, COMPTE) AS 
  SELECT 
vd.ID,
vd.IDVENTE,
vd.IDPRODUIT,
p.VAL AS idProduitLib,
vd.IDORIGINE,
vd.QTE,
vd.PU,
vd.REMISE,
vd.TVA,
vd.PUACHAT,
vd.PUVENTE,
vd.IDDEVISE,
vd.TAUXDECHANGE,
vd.DESIGNATION,
vd.COMPTE 
FROM
VENTE_DETAILS vd
LEFT JOIN PRODUIT p ON p.ID = vd.IDPRODUIT ;