ALTER TABLE HISTORIQUEPUING
ADD IDINGREDIENTS VARCHAR2(50);

ALTER TABLE HISTORIQUEPUING
ADD CONSTRAINT fk_idingredient
FOREIGN KEY (IDINGREDIENTS) REFERENCES AS_INGREDIENTS(ID);


ALTER TABLE HISTORIQUEPVING
ADD IDINGREDIENTS VARCHAR2(50);

ALTER TABLE HISTORIQUEPVING
ADD CONSTRAINT fk_idingredient2
FOREIGN KEY (IDINGREDIENTS) REFERENCES AS_INGREDIENTS(ID);