create or replace view FACTUREFOURNISSEURFILLECPL as
SELECT 
f.ID ,
f.IDFACTUREFOURNISSEUR ,
f.IDPRODUIT ,
p.LIBELLE AS IDPRODUITLIB,
f.QTE ,
f.PU ,
f.REMISES ,
f.IDBCDETAIL ,
f.TVA ,
f.IDDEVISE,
f2.DATY,
CAST(f.QTE * f.PU AS NUMBER(30,2)) AS montantht,
CAST(f.QTE * f.PU + (f.QTE * f.PU * f.TVA/100) AS NUMBER(30,2)) AS montantttc,
CAST(f.QTE * f.PU * f.TVA/100 AS NUMBER(30,2)) AS montanttva,
CAST((nvl(f.remises/100,0))*(f.QTE * f.PU) AS NUMBER(30,2)) AS montantRemise,
CAST((1-nvl(f.remises/100,0))*(f.QTE * f.PU) AS NUMBER(30,2)) AS montant
FROM FACTUREFOURNISSEURFILLE f 
LEFT JOIN FACTUREFOURNISSEUR f2 ON f2.ID = f.IDFACTUREFOURNISSEUR 
LEFT JOIN AS_INGREDIENTS p ON p.ID = f.IDPRODUIT
/

create view FFFILLECPL_VISEE as
SELECT
    f.ID ,
    f.IDFACTUREFOURNISSEUR ,
    f.IDPRODUIT ,
    p.LIBELLE AS IDPRODUITLIB,
    f.QTE ,
    f.PU ,
    f.REMISES ,
    f.IDBCDETAIL ,
    f.TVA ,
    f.IDDEVISE,
    f2.DATY,
    c.ID  AS IDCATEGORIE,
    c.VAL AS IDCATEGORIELIB,
    CAST(f.QTE * f.PU AS NUMBER(30,2)) AS montantht,
    CAST(f.QTE * f.PU + (f.QTE * f.PU * f.TVA/100) AS NUMBER(30,2)) AS montantttc,
    CAST(f.QTE * f.PU * f.TVA/100 AS NUMBER(30,2)) AS montanttva,
    CAST((nvl(f.remises/100,0))*(f.QTE * f.PU) AS NUMBER(30,2)) AS montantRemise,
    CAST((1-nvl(f.remises/100,0))*(f.QTE * f.PU) AS NUMBER(30,2)) AS montant
FROM FACTUREFOURNISSEURFILLE f
         LEFT JOIN FACTUREFOURNISSEUR f2 ON f2.ID = f.IDFACTUREFOURNISSEUR
         LEFT JOIN AS_INGREDIENTS p ON p.ID = f.IDPRODUIT
         LEFT JOIN PRODUIT pp ON p.ID = f.IDPRODUIT
         LEFT JOIN CATEGORIE c  ON pp.IDCATEGORIE  = c.ID
where f2.ETAT >= 11
/

create view FFFILLECPL_MONTANT as
SELECT 
f.ID ,
f.IDFACTUREFOURNISSEUR ,
f.IDPRODUIT ,
nvl(i.LIBELLE,p.VAL) AS IDPRODUITLIB,
f.QTE ,
f.PU ,
f.REMISES ,
f.IDBCDETAIL,
f.TVA,
nvl(f.QTE*f.PU,0) AS MONTANTTOTAL,
p2.ID AS IDPOINT,
p2.VAL AS IDPOINTLIB,
m.ID AS IDMAGASIN,
m.VAL  AS IDMAGASINLIB,
c.ID  AS IDCATEGORIE,
c.VAL AS IDCATEGORIELIB,
f2.DATY AS daty,
f.IDDEVISE
FROM FACTUREFOURNISSEURFILLE f 
LEFT JOIN FACTUREFOURNISSEUR f2 ON f2.ID = f.IDFACTUREFOURNISSEUR 
LEFT JOIN MAGASIN m ON m.ID = f2.IDMAGASIN 
LEFT JOIN POINT p2 ON m.IDPOINT = p2.ID  
LEFT JOIN PRODUIT p ON p.ID = f.IDPRODUIT
LEFT JOIN CATEGORIE c  ON p.IDCATEGORIE  = c.ID
LEFT JOIN AS_INGREDIENTS i ON i.ID = f.IDPRODUIT
/

