------2025-04-08
--------Tiavina

--------attacher fichier
--Existant
--CREATE TABLE attacher_fichier (
--    id VARCHAR2(100) NOT NULL,
--    chemin VARCHAR2(500) NULL,
--    libelle CLOB NULL,
--    mere VARCHAR2(100) NOT NULL,
--    daty TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL
--);


CREATE OR REPLACE FUNCTION getseq_attacher_fichier
   RETURN NUMBER
IS
   retour   NUMBER;
BEGIN
   SELECT SEQ_ATTACHER_FICHIER.NEXTVAL INTO retour FROM DUAL;

   RETURN retour;
END;

INSERT INTO menudynamique (id, libelle, icone, href, rang, niveau, id_pere) 
VALUES ('MENUP001V', 'Gestion électronique des documents', 'fa fa-folder-o', null, 8, 1, null);

INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0804001', '*', 'MENUP001V', NULL, NULL, NULL, NULL);


INSERT INTO menudynamique (id, libelle, icone, href, rang, niveau, id_pere) 
VALUES ('MENUP0011V', 'Liste', 'fa fa-list', '/giz/pages/module.jsp?but=filemanager/file-liste-2.jsp', 1, 2, 'MENUP001V');

-----corriger  icone menu


UPDATE MENUDYNAMIQUE
SET  ICONE='fa fa-plus'
WHERE ID='MNDN000000021111151';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN000000021111152';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MNDN000000021111121';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN000000021111122';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MNDN000000021111131';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN000000021111132';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MNDN0000000211111331';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN0000000211111332';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MNDN000000021111141';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN000000021111142';

UPDATE MENUDYNAMIQUE
SET  ICONE='fa fa-plus'
WHERE ID='MENUDYN00151';
UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MENUDYN00161';
UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MENUDYN00171';
UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MENUDYN00173';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='MNDN000021';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-plus'
WHERE ID='STATIM0003';


UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELM001060';
UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELM001063';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELMT001060';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELMT001063';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELMT001038';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELMT000395';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELMT000417';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELMT000419';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN0000000202';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN312';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='MNDN0000000122';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='ELM001043';

UPDATE MENUDYNAMIQUE
SET ICONE='fa fa-list'
WHERE ID='STATIM0002';

--Ny zanaky ny menus Production iany 
--Ze libellé saisie ovaina libellé hoe création 

UPDATE MENUDYNAMIQUE
SET LIBELLE='Création'
WHERE ID='MENUDYN0304008';

UPDATE MENUDYNAMIQUE
SET LIBELLE='Création'
WHERE ID='MENUDYN3204004';


------- ajout libelle exacte
UPDATE AS_INGREDIENTS
SET LIBELLE='farine de ble', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=11, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71001', COMPTE_ACHAT='61001', LIBELLEEXTACTE='farine de bl&eacute;'
WHERE ID='PB0011';

UPDATE AS_INGREDIENTS
SET LIBELLE='farine  complete', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71002', COMPTE_ACHAT='61002', LIBELLEEXTACTE='farine  compl&egrave;te'
WHERE ID='PB0012';

UPDATE AS_INGREDIENTS
SET LIBELLE='farine  sans gluten', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=6, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71003', COMPTE_ACHAT='61003', LIBELLEEXTACTE='farine  sans gluten'
WHERE ID='PB0013';

UPDATE AS_INGREDIENTS
SET LIBELLE='levure fraiche', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71004', COMPTE_ACHAT='61004', LIBELLEEXTACTE='levure fra&icirc;che'
WHERE ID='PB0014';

UPDATE AS_INGREDIENTS
SET LIBELLE='levure chimique', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71005', COMPTE_ACHAT='61005', LIBELLEEXTACTE='levure chimique'
WHERE ID='PB0015';

UPDATE AS_INGREDIENTS
SET LIBELLE='levure seche', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71006', COMPTE_ACHAT='61006', LIBELLEEXTACTE='levure s&egrave;che'
WHERE ID='PB0016';

UPDATE AS_INGREDIENTS
SET LIBELLE='eau', SEUIL=0, UNITE='UNT00006', QUANTITEPARPACK=0, PU=1000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71007', COMPTE_ACHAT='61007', LIBELLEEXTACTE='eau'
WHERE ID='PB0017';

UPDATE AS_INGREDIENTS
SET LIBELLE='sel', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=2, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71008', COMPTE_ACHAT='61008', LIBELLEEXTACTE='sel'
WHERE ID='PB0018';

UPDATE AS_INGREDIENTS
SET LIBELLE='sucre', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=4, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='71009', COMPTE_ACHAT='61009', LIBELLEEXTACTE='sucre'
WHERE ID='PB0019';

UPDATE AS_INGREDIENTS
SET LIBELLE='lait', SEUIL=0, UNITE='UNT00004', QUANTITEPARPACK=0, PU=3, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710010', COMPTE_ACHAT='610010', LIBELLEEXTACTE='lait'
WHERE ID='PB0020';

UPDATE AS_INGREDIENTS
SET LIBELLE='oeuf', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=500, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710011', COMPTE_ACHAT='610011', LIBELLEEXTACTE='&oelig;uf'
WHERE ID='PB0021';

UPDATE AS_INGREDIENTS
SET LIBELLE='sesame', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=8, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710012', COMPTE_ACHAT='610012', LIBELLEEXTACTE='s&eacute;same'
WHERE ID='PB0022';

UPDATE AS_INGREDIENTS
SET LIBELLE='amande', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT001', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='710013', COMPTE_ACHAT='610013', LIBELLEEXTACTE='amande'
WHERE ID='PB0023';

UPDATE AS_INGREDIENTS
SET LIBELLE='petrissage', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=10, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT004', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72001', COMPTE_ACHAT='62001', LIBELLEEXTACTE='p&eacute;trissage'
WHERE ID='S0001';

UPDATE AS_INGREDIENTS
SET LIBELLE='faconnage', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=10000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT004', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72002', COMPTE_ACHAT='62002', LIBELLEEXTACTE='fa&ccedil;onnage'
WHERE ID='S0002';

UPDATE AS_INGREDIENTS
SET LIBELLE='cuisson four', SEUIL=0, UNITE='UNT00009', QUANTITEPARPACK=0, PU=2, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT006', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72003', COMPTE_ACHAT='62003', LIBELLEEXTACTE='cuisson four'
WHERE ID='S0003';

UPDATE AS_INGREDIENTS
SET LIBELLE='cuisson', SEUIL=0, UNITE='UNT00009', QUANTITEPARPACK=0, PU=1, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=0, CATEGORIEINGREDIENT='CAT005', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=0, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='72004', COMPTE_ACHAT='62004', LIBELLEEXTACTE='cuisson'
WHERE ID='S0004';

UPDATE AS_INGREDIENTS
SET LIBELLE='pâte standard', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=8, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=10, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73001', COMPTE_ACHAT='63001', LIBELLEEXTACTE='p&acirc;te standard'
WHERE ID='PF0011';

UPDATE AS_INGREDIENTS
SET LIBELLE='pate complete', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=10, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=12, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73002', COMPTE_ACHAT='63002', LIBELLEEXTACTE='p&acirc;te compl&egrave;te'
WHERE ID='PF0012';

UPDATE AS_INGREDIENTS
SET LIBELLE='pate sans gluten', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=12, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=14, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73003', COMPTE_ACHAT='63003', LIBELLEEXTACTE='p&acirc;te sans gluten'
WHERE ID='PF0013';

UPDATE AS_INGREDIENTS
SET LIBELLE='pate viennoiserie', SEUIL=0, UNITE='UNT00001', QUANTITEPARPACK=0, PU=18, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT007', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=20, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='73004', COMPTE_ACHAT='63004', LIBELLEEXTACTE='p&acirc;te viennoiserie'
WHERE ID='PF0014';

UPDATE AS_INGREDIENTS
SET LIBELLE='baguette', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=3000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=4000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74001', COMPTE_ACHAT='64001', LIBELLEEXTACTE='baguette'
WHERE ID='PV0014';

UPDATE AS_INGREDIENTS
SET LIBELLE='pain complet', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=6000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8001, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74002', COMPTE_ACHAT='64002', LIBELLEEXTACTE='pain complet'
WHERE ID='PV0015';

UPDATE AS_INGREDIENTS
SET LIBELLE='baguette sans gluten', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=8000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=12000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74003', COMPTE_ACHAT='64003', LIBELLEEXTACTE='baguette sans gluten'
WHERE ID='PV0016';

UPDATE AS_INGREDIENTS
SET LIBELLE='pain sesame', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=6000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT002', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74004', COMPTE_ACHAT='64004', LIBELLEEXTACTE='pain s&eacute;same'
WHERE ID='PV0017';

UPDATE AS_INGREDIENTS
SET LIBELLE='croissant', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=5000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT003', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=8000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74005', COMPTE_ACHAT='64005', LIBELLEEXTACTE='croissant'
WHERE ID='PV0018';

UPDATE AS_INGREDIENTS
SET LIBELLE='croissant aux amandes', SEUIL=0, UNITE='UNT00005', QUANTITEPARPACK=0, PU=8000, ACTIF=1, PHOTO=NULL, CALORIE=0, DURRE=0, COMPOSE=1, CATEGORIEINGREDIENT='CAT003', IDFOURNISSEUR=NULL, DATY=NULL, QTELIMITE=0, PV=9000, LIBELLEVENTE=NULL, SEUILMIN=NULL, SEUILMAX=NULL, PUACHATUSD=NULL, PUACHATEURO=NULL, PUACHATAUTREDEVISE=NULL, PUVENTEUSD=NULL, PUVENTEEURO=NULL, PUVENTEAUTREDEVISE=NULL, ISVENTE=NULL, ISACHAT=NULL, COMPTE_VENTE='74006', COMPTE_ACHAT='64006', LIBELLEEXTACTE='croissant aux amandes'
WHERE ID='PV0019';
