-- CREATE OR REPLACE VIEW RESERVATIONCALENDRIER AS
-- SELECT r.* FROM RESERVATIONDETAILS_LIB r
--                     LEFT JOIN RESERVATION rmere ON r.IDMERE = rmere.ID
-- WHERE rmere.ETAT >= 11;

CREATE OR REPLACE VIEW RESERVATIONCALENDRIER AS
SELECT r.* FROM RESERVATION_LIB r WHERE ETAT>=11;

INSERT INTO MENUDYNAMIQUE (ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE) VALUES
    ('ELM01','Planning','fa fa-calendar','module.jsp?but=reservation/reservation-calendrier-v2.jsp',4,2,'ELM001104004');

