--creer VIEW FABRICATIONCPL: lancerparLib, cibleLib
CREATE VIEW FABRICATIONCPL 
AS 
SELECT 
f.*,
p.val AS lanceparLib,
p2.val AS cibleLib
FROM FABRICATION f 
LEFT JOIN POINT p ON p.id = f.lancepar 
LEFT JOIN POINT p2 ON p2.id = f.cible;

CREATE VIEW FABRICATIONFILLECPL 
AS 
SELECT 
f.*,
ai.LIBELLE AS idingredientsLib
FROM FABRICATIONFILLE f 
LEFT JOIN AS_INGREDIENTS ai ON ai.id = f.IDINGREDIENTS;


INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN00304001', 'Production', 'fa fa-industry', NULL, 12, 1, NULL);

INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMEN0304001', '*', 'MENUDYN00304001', NULL, NULL, NULL, NULL);

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN00304002', 'Fabrication', 'fa fa-cogs', NULL, 1, 2, 'MENUDYN00304001');


INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0304008', 'Saisie', 'fa fa-plus', 'module.jsp?but=fabrication/fabrication-saisie.jsp', 1, 3, 'MENUDYN00304002');

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0304009', 'Liste', 'fa fa-list', 'module.jsp?but=fabrication/fabrication-liste.jsp', 2, 3, 'MENUDYN00304002');


INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN00304003', 'Ordre de fabrication', 'fa fa-file-alt', NULL, 2, 2, 'MENUDYN00304001');


INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN3204004', 'Saisie', 'fa fa-plus', 'module.jsp?but=fabrication/ordre-fabrication-saisie.jsp', 1, 3, 'MENUDYN00304003');

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MENUDYN0304005', 'Liste', 'fa fa-list', 'module.jsp?but=fabrication/ordre-fabrication-liste.jsp', 2, 3, 'MENUDYN00304003');