ALTER TABLE FABRICATION ADD (etat NUMBER(38, 0) DEFAULT 1 NOT NULL);

CREATE OR REPLACE VIEW FABRICATIONCPL ("ID", "LANCEPAR", "CIBLE", "REMARQUE", "LIBELLE", "BESOIN", "DATY", "IDOF", "LANCEPARLIB", "CIBLELIB", "ETAT","ETATLIB") AS 
  SELECT 
f.ID,f.LANCEPAR,f.CIBLE,f.REMARQUE,f.LIBELLE,f.BESOIN,f.DATY,f.IDOF,
p.val AS lanceparLib,
p2.val AS cibleLib,
f.etat AS etat,
CASE
		WHEN f.ETAT=1
		THEN 'CREE'
		WHEN f.ETAT=11
		THEN 'VALIDEE'
		WHEN f.ETAT=0
		THEN 'ANNULEE'
	    WHEN f.ETAT=21
		THEN 'ENTAME'
	    WHEN f.ETAT=31
		THEN 'BLOQUE'
	    WHEN f.ETAT=41
		THEN 'TERMINEE'
	END AS ETATLIB
FROM FABRICATION f 
LEFT JOIN POINT p ON p.id = f.lancepar 
LEFT JOIN POINT p2 ON p2.id = f.cible;


CREATE OR REPLACE VIEW MVTSTOCKLIB ("ID", "DESIGNATION", "IDMAGASIN","IDOBJET", "IDMAGASINLIB", "IDVENTE", "IDVENTELIB", "IDTRANSFERT", "IDTRANSFERTLIB", "IDTYPEMVSTOCK", "IDTYPEMVSTOCKLIB", "DATY", "ETAT", "ETATLIB") AS 
  SELECT 
m.ID ,
m.DESIGNATION ,
m.IDMAGASIN ,
m.IDOBJET ,
m2.VAL  AS idMagasinlib,
m.IDVENTE ,
v.DESIGNATION  AS idVentelib,
m.IDTRANSFERT ,
CAST('' AS VARCHAR2(255)) AS idTransfertlib,
m.IDTYPEMVSTOCK ,
t.VAL AS idTypeMvStocklib ,
m.DATY ,
m.ETAT ,
CASE 
	WHEN m.ETAT = 0 
	THEN 'ANNULEE'  
	WHEN m.ETAT = 1 
	THEN 'CREE'
	WHEN m.ETAT = 11 
	THEN 'VALIDEE'
END AS etatlib
FROM MVTSTOCK m 
LEFT JOIN TYPEMVTSTOCK t ON t.ID = m.IDTYPEMVSTOCK 
LEFT JOIN VENTE v ON v.ID = m.IDVENTE 
LEFT JOIN MAGASIN m2 ON m2.ID = m.IDMAGASIN ;


CREATE OR REPLACE VIEW FabricationMereFille AS SELECT ff.IDINGREDIENTS,ff.IDINGREDIENTSLIB ,sum(ff.QTE) qte,ff.IDUNITE ,f.IDOF FROM FabricationFilleCpl ff JOIN FABRICATION f ON f.id=ff.IDMERE WHERE f.etat=11 GROUP BY ff.IDINGREDIENTS,ff.IDINGREDIENTSLIB ,ff.IDUNITE ,f.IDOF; 

CREATE OR REPLACE VIEW OfFilleResteLib AS SELECT o.*,fmf.qte AS qteFabrique,(o.qte-fmf.qte) AS qteReste FROM FabricationMereFille fmf JOIN OfFilleLib o ON fmf.idof=o.IDMERE  AND fmf.IDINGREDIENTS=o.IDINGREDIENTS 
