INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDNU00001', 'Utilisateur', 'fa fa-tags', NULL, 12, 1, NULL);

INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDNU000011', 'Inscription', 'fa fa-plus', 'module.jsp?but=utilisateur/utilisateur-saisie.jsp', 1, 2, 'MNDNU00001');
INSERT INTO MENUDYNAMIQUE
(ID, LIBELLE, ICONE, HREF, RANG, NIVEAU, ID_PERE)
VALUES('MNDNU000012', 'Liste Utilisateur', 'fa fa-list', 'module.jsp?but=utilisateur/utilisateur-liste.jsp', 2, 2, 'MNDNU00001');

INSERT INTO USERMENU
(ID, REFUSER, IDMENU, IDROLE, CODESERVICE, CODEDIR, INTERDIT)
VALUES('USRMENU01104004', '*', 'MNDNU00001', NULL, NULL, NULL, NULL);
