CREATE TABLE DMDACHAT (
    id VARCHAR(50) PRIMARY KEY,
	daty DATE,
	fournisseur VARCHAR(50),
	remarque VARCHAR(255),
	FOREIGN KEY (fournisseur) REFERENCES FOURNISSEUR(ID)
);

CREATE SEQUENCE SEQ_DMDACHAT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE OR REPLACE FUNCTION GETSEQDMDACHAT
    RETURN NUMBER IS
    retour NUMBER;
BEGIN
    SELECT SEQ_DMDACHAT.nextval INTO retour FROM dual;
    return retour;
END;


CREATE TABLE DMDACHATFILLE (
    id VARCHAR(50) PRIMARY KEY,
    idmere VARCHAR(50),
	idproduit VARCHAR(50),
	designation VARCHAR(255),
	quantite NUMBER(20, 2),
	pu NUMBER(20, 2),
	tva NUMBER(20,2),
	FOREIGN KEY (idmere) REFERENCES DMDACHAT(ID),
	FOREIGN KEY (idproduit) REFERENCES AS_INGREDIENTS(ID)
);

CREATE SEQUENCE SEQ_DMDACHATFILLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE OR REPLACE FUNCTION GETSEQDMDACHATFILLE
    RETURN NUMBER IS
    retour NUMBER;
BEGIN
    SELECT SEQ_DMDACHATFILLE.nextval INTO retour FROM dual;
    return retour;
END;


CREATE OR REPLACE VIEW DMDACHATLIB AS
SELECT
da.id,
da.daty,
da.fournisseur,
f.nom AS fournisseurlib,
da.remarque
FROM DMDACHAT da
LEFT JOIN FOURNISSEUR f ON f.ID = da.fournisseur;