ALTER TABLE VOITURE  ADD priorite NUMBER DEFAULT 0;

-- LOCATION.VOITURELIBELLEMONTANT source


-- LOCATION.VOITURELIBELLE source avant 

CREATE OR REPLACE VIEW VOITURELIBELLE (ID, NOM, COULEUR, NUMERO, GPS, CHARGE_PER_KILOMETRE, VALEUR_ACTUELLE, KILOMETRAGE_ACTUEL, CONSOMMATION, ENERGIE, NBPLACE, CATEGORIE, ETATGENERALE, ESTENPANNE, CATEGORIELIBELLE) AS 
  select v.ID,v.NOM,v.COULEUR,v.NUMERO,v.GPS,v.CHARGE_PER_KILOMETRE,v.VALEUR_ACTUELLE,v.KILOMETRAGE_ACTUEL,v.CONSOMMATION,v.ENERGIE,v.NBPLACE,v.CATEGORIE,v.ETATGENERALE,v.ESTENPANNE,c.VAL as categorieLibelle
from voiture v
left join CATEGORIEVOITURE c on v.CATEGORIE=c.ID;
-- LOCATION.VOITURELIBELLE source apres

-- LOCATION.VOITURELIBELLE source

CREATE OR REPLACE VIEW VOITURELIBELLE (ID, NOM, COULEUR, NUMERO, GPS, CHARGE_PER_KILOMETRE, VALEUR_ACTUELLE, KILOMETRAGE_ACTUEL, CONSOMMATION, 
ENERGIE, NBPLACE, CATEGORIE, ETATGENERALE, ESTENPANNE, CATEGORIELIBELLE,PRIORITE) AS 
  select v.ID,v.NOM,v.COULEUR,v.NUMERO,v.GPS,v.CHARGE_PER_KILOMETRE,v.VALEUR_ACTUELLE,v.KILOMETRAGE_ACTUEL,v.CONSOMMATION,v.ENERGIE,v.NBPLACE,v.CATEGORIE,
  v.ETATGENERALE,v.ESTENPANNE,c.VAL as categorieLibelle , v.PRIORITE AS PRIORITE
from voiture v
left join CATEGORIEVOITURE c on v.CATEGORIE=c.ID ORDER BY v.PRIORITE asc;


SELECT * FROM VOITURELIBELLE;


-- new VOITURELIBELLEMONTANT


CREATE OR REPLACE VIEW VOITURELIBELLEMONTANT1 (ID, NOM, COULEUR, NUMERO, GPS, CHARGE_PER_KILOMETRE, VALEUR_ACTUELLE, KILOMETRAGE_ACTUEL, CONSOMMATION,
ENERGIE, NBPLACE, CATEGORIE, ETATGENERALE, ESTENPANNE, CATEGORIELIBELLE, MONTANTRESA, CHARGE, MARGE,PRIORITE) AS 
  select v.ID,v.NOM,v.COULEUR,v.NUMERO,v.GPS,v.CHARGE_PER_KILOMETRE,v.VALEUR_ACTUELLE,v.KILOMETRAGE_ACTUEL,v.CONSOMMATION,v.ENERGIE,v.NBPLACE,v.CATEGORIE,v.ETATGENERALE,v.ESTENPANNE,v.CATEGORIELIBELLE, cast(nvl(r.montant,0)as number(30,2)) as montantResa,
  cast(nvl(ff.montant,0) as number(30,2)) as charge, cast(nvl(r.montant,0)-nvl(ff.montant,0)as number(30,2)) as marge,v.PRIORITE AS PRIORITE  from VOITURELIBELLE v
left join reservationDetGroupeVoiture r on v.ID=r.IDVOITURE
left join factureFournGroupeVoiture ff on v.ID=ff.IDVOITURE ORDER BY PRIORITE ASC ;


