UPDATE USERMENU SET INTERDIT=NULL WHERE ID='USRMEN09';
CREATE OR REPLACE VIEW MVTSTOCKFILLELIB (ID, IDMVTSTOCK, IDPRODUIT, IDPRODUITLIB, ENTREE, SORTIE, IDVENTEDETAIL, IDVENTEDETAILLIB, IDTRANSFERTDETAIL, IDTRANSFERTDETAILLIB, DATY, IDMAGASIN, IDMAGASINLIB, PU, MONTANT, LIBELLEEXACTE) AS 
  SELECT
	m.ID ,
	m.IDMVTSTOCK ,
	m.IDPRODUIT ,
	p.libelle  AS IDPRODUITLIB,
	m.ENTREE ,
	m.SORTIE ,
	m.IDVENTEDETAIL ,
	'' AS IDVENTEDETAILLIB,
	m.IDTRANSFERTDETAIL ,
	'' AS IDTRANSFERTDETAILLIB,
	m2.DATY ,
	m2.IDMAGASIN ,
	m3.VAL AS IDMAGASINLIB,
	m.pu,
    cast(m.pu*m.ENTREE+(m.pu*m.sortie) as number(20,2)) as montant,
    p.LIBELLE
	FROM MVTSTOCKFILLE m
	LEFT JOIN AS_INGREDIENTS  p ON p.ID = m.IDPRODUIT
	LEFT JOIN MVTSTOCK m2 ON m2.ID = m.IDMVTSTOCK
	LEFT JOIN MAGASIN m3 ON m3.ID = m2.IDMAGASIN;

	CREATE OR REPLACE  VIEW CHECKINLIBELLE (ID, RESERVATION, IDRESERVATIONMERE, DATY, HEURE, REMARQUE, CLIENT, IDPRODUIT, ETAT, IDCLIENT, CHECKOUT, PRODUITLIBELLE, PU, TVA, ETATLIB, KILOMETRAGECHECKIN, KILOMETRAGECHECKOUT, DISTANCEREELLE, QUANTITE, EQUIVALENCE,QTE) AS 
  SELECT
	c.ID,
	c.RESERVATION,
	nvl(r2.ID,c.reservation) AS idReservationMere,
	c.DATY,
	c.HEURE,
	c.REMARQUE,
	cl.nom AS CLIENT,
	c.IDPRODUIT,
	c.ETAT,
	c.IDCLIENT,
	c.CHECKOUT,
	i.LIBELLE AS produitLibelle,
	i.pu,
	i.tva,
	CASE
	WHEN c.ETAT = 0
	THEN 'ANNULEE'
	WHEN c.ETAT = 1
	THEN 'CREE'
	WHEN c.ETAT = 11
	THEN 'VISEE'
END AS ETATLIB,
	c.kilometragecheckin,
	c.kilometragecheckout,
	c.distancereelle,
	c.quantite,
	u.EQUIVALENCE,
	c.qte
FROM
	checkInAvecChekOut c
LEFT JOIN RESERVATIONDETAILS r ON r.ID = c.RESERVATION 
LEFT JOIN RESERVATION r2 ON r.IDMERE = r2.id
LEFT JOIN AS_INGREDIENTS i ON c.IDPRODUIT = i.id
LEFT JOIN CLIENT cl ON c.IDCLIENT=cl.id
left join AS_UNITE u on i.UNITE=u.ID;


CREATE OR REPLACE  VIEW CHECKOUTLIB (ID, RESERVATION, IDRESERVATIONMERE, DATY, HEURE, REMARQUE, ETAT, PRODUITLIBELLE, ETATLIB, KILOMETRAGECHECKIN, KILOMETRAGECHECKOUT, DISTANCEREELLE, QUANTITE,PU,IDPRODUIT) AS 
  select
    ch.ID,ci.ID as RESERVATION,ci.IDRESERVATIONMERE,ch.DATY,ch.HEURE,ch.REMARQUE,ch.ETAT,
    ci.PRODUITLIBELLE,
    case when ch.ETAT = 1 then 'CREE'
    when ch.ETAT = 11 then 'VALIDEE'
    END as etatlib,
    ci.kilometragecheckin,
    ch.KILOMETRAGE as kilometragecheckout,
    ci.distancereelle,
    ch.quantite,
    ci.pu,
    ci.idproduit
from CHECKOUT ch
join CHECKINLIBELLE ci on ci.ID = ch.RESERVATION;