CREATE OR REPLACE FORCE VIEW "ASYNCLOCATION"."HISTORIQUERESERVATIONVOITURE_1" ("ID", "IDMERE", "QTE", "DATY", "IDPRODUIT", "LIBELLEPRODUIT", "CATEGORIEPRODUIT", "PU", "MONTANT", "TVA", "MONTANTTVA", "MONTANTTTC", "CATEGORIEPRODUITLIB", "HEURE", "DISTANCEESTIMATION", "KILOMETRAGECHECKIN", "KILOMETRAGECHECKOUT", "DISTANCEREELLE", "CHARGE_PER_KILOMETRE", "VALEUR_ACTUELLE", "REVIENT", "MARGE", "IDCHECKIN", "IDCHECKOUT", "IDVOITURE", "ETAT","IDCLIENT","IDCLIENTLIB") AS

select e.id AS "ID",e.IDMERE AS "IDMERE",e.QTE as "QTE",e.DATY AS "DATY",e.IDPRODUIT as "IDPRODUIT",e.LIBELLEPRODUIT AS "LIBELLEPRODUIT",
e.CATEGORIEPRODUIT AS "CATEGORIEPRODUIT",e.PU AS "PU", 
e.MONTANT AS "MONTANT",e.TVA AS "TVA",e.MONTANTTVA AS  "MONTANTTVA",e.MONTANTTTC AS  "MONTANTTTC",
e.CATEGORIEPRODUITLIB AS "CATEGORIEPRODUITLIB", e.HEURE AS "HEURE",e.DISTANCEESTIMATION AS  "DISTANCEESTIMATION",
e.KILOMETRAGECHECKIN AS "KILOMETRAGECHECKIN",e.KILOMETRAGECHECKOUT AS "KILOMETRAGECHECKOUT",e.DISTANCEREELLE AS "DISTANCEREELLE",
e.CHARGE_PER_KILOMETRE AS "CHARGE_PER_KILOMETRE",e.VALEUR_ACTUELLE AS "VALEUR_ACTUELLE",e.REVIENT AS "REVIENT",
e.MARGE AS "MARGE",e.IDCHECKIN AS "IDCHECKIN",e.IDCHECKOUT AS "IDCHECKOUT",e.IDVOITURE AS "IDVOITURE",e.ETAT AS "ETAT", r.IDCLIENT AS IDCLIENT , c.NOM AS idclientlib
  from RESERVATIONDETAILS_LIB_MARGE e 
  JOIN RESERVATION r ON r.ID = e.IDMERE
  JOIN CLIENT c ON c.ID  = r.IDCLIENT 
  where e.etat >= 11
  
  ;
  

   SELECT * FROM  HISTORIQUERESERVATIONVOITURE_1;